Feature/authentification
MisterAzix/hetic-saline-royale-academy pull request #17
Opened 2023-06-06 14:00 UTC by justinDev91

## Ticket
ETQ dev JV implementer l’authentification JWT, Passport, OAuth

## Infos

Implémentation de l'authentification, de l'inscription avec mot de passe, JWT et Google OAuth avec Prisma

Description détaillée du commit :

Ajout de l'authentification et de l'inscription avec mot de passe, JWT et Google OAuth.
Utilisation de Prisma pour la gestion des données.
Mise en place des fonctionnalités permettant aux utilisateurs de s'inscrire en utilisant leur adresse e-mail et mot de passe, ainsi que de se connecter avec ces identifiants.
Ajout de la possibilité de s'inscrire et de se connecter via Google OAuth, en utilisant le flux d'autorisation OAuth de Google.
Utilisation de JWT (JSON Web Tokens) pour gérer l'authentification des utilisateurs et sécuriser les sessions.
Les données des utilisateurs, telles que les identifiants et les informations de profil, sont stockées dans la base de données à l'aide de Prisma et posgreql.

2023-06-06 14:19 UTC, MisterAzix requested changes

2023-06-06 14:19 UTC, MisterAzix commented on apps/api/.gitignore
Dans le .gitignore global stp

2023-06-06 14:19 UTC, MisterAzix commented on .gitignore
> +package-lock.json
Non jamais
```suggestion
```

2023-06-06 14:19 UTC, MisterAzix commented on .gitignore
> +package.json
```suggestion
```

2023-06-06 14:19 UTC, MisterAzix commented on docker-compose.yml
> +      - "5555:5432"
Pourquoi ? 🤔 
A la limite ajouter une variable d'env, si t'as besoin de le changer de ton côté
```suggestion
      - "${POSTGRES_PORT:-5432}:5432"
```

2023-06-06 15:41 UTC, justinDev91 commented on apps/api/.gitignore
ok

2023-06-06 15:41 UTC, justinDev91 commented on .gitignore
> +package-lock.json
supprimé

2023-06-06 15:41 UTC, justinDev91 commented on .gitignore
> +package.json
done

2023-06-06 16:00 UTC, justinDev91 commented on docker-compose.yml
> +      - "5555:5432"
Ok

2023-06-06 16:10 UTC, justinDev91 commented on apps/api/src/helper/helper.services.ts
> +    const randomIndex = randomBytes(1)[0] % charactersLength;
c'est done

2023-06-08 12:36 UTC, MisterAzix approved these changes

2023-06-08 12:44 UTC, merged