feat(front-client): display and update user info
MisterAzix/hetic-saline-royale-academy pull request #82
Opened 2023-08-22 16:15 UTC by benoitfvr

## Preview

https://github.com/MisterAzix/hetic-saline-royale-academy/assets/61755435/97fce43d-d80b-48c1-9bbc-7fd3f9190e88

## Erreurs

1. Erreur CORS quand j'essaie de update

https://github.com/MisterAzix/hetic-saline-royale-academy/assets/61755435/daffa668-c8c4-4a25-9bc2-4654a1e820ab

2. Ce bout de code m'empêche de update le user

https://github.com/MisterAzix/hetic-saline-royale-academy/assets/61755435/4d9760e7-e1a9-4c60-933b-0d255e3759db

2023-08-22 18:02 UTC, MisterAzix requested changes
De manière général, là tu fais tout dans ta page, le hook est pas forcément au bon endroit, c'est un peu le bazard. Donc hésite pas à faire une feature, comme pour le login, le register ou encore ce que j'ai fait dans ma PR en DRAFT #78

Enjoy <3

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/features/sidebar/components/Molecules/Profile.tsx
> +  }
Okay alors ici en vrai je retournerais juste `null`, parce qu'au final le seul moment où tu rentres dans ce cas c'est quand la data charge, et vaut mieux ne rien afficher qu'un message un peu faux

```suggestion
  if (!user) {
    return null;
  }
```

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/features/sidebar/components/Molecules/Profile.tsx
> +  };
Pourquoi c'est des fonctions ?
(Vraiment nécessaire le `.trim()` ? 🤔 
```suggestion
  const fullname = `${user.first_name} ${user.last_name}`.trim();
  const email = user.email || 'Email not provided';
```

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/features/sidebar/components/Molecules/Profile.tsx
> +          <DescriptionText>{getEmail()}</DescriptionText>
```suggestion
          <TitleText>{fullname}</TitleText>
          <DescriptionText>{email}</DescriptionText>
```

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/features/sidebar/hooks/useUpdateUser.ts
> +      Authorization: `Bearer ${access_token}`,
Il manque le Content-Type je pense que la CORS error vient de là, autant un POST il est capable de le deviner autant sur un PATCH je pense pas.
```suggestion
      Authorization: `Bearer ${access_token}`,
      'Content-Type': 'application/json',
```

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/features/sidebar/hooks/useUpdateUser.ts
> +  const mutation = useMutation(
```suggestion
  const { mutate, isLoading, isError } = useMutation(
```

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/features/sidebar/hooks/useUpdateUser.ts
> +  return mutation;
```suggestion
  return { submitUpdateUserForm: mutate, isLoading, isError };;
```

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/pages/profile/index.tsx
> +  const updateUserMutation = useUpdateUser();
```suggestion
  const { submitRegisterForm, isLoading, isError } = useUpdateUser();
```

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/pages/profile/index.tsx
> +  const [message, setMessage] = useState('');
Regarde `react-hook-form`, ça va te simplifier la vie, tu t'embêtes pour rien :)

Tu peux t'inspirer de : `apps/front-client/src/features/register/components/Organisms/RegisterForm.tsx`

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/pages/profile/index.tsx
> +  }, [user]);
Beurk on veut pas de useEffect <3

2023-08-22 18:02 UTC, MisterAzix commented on apps/front-client/src/pages/profile/index.tsx
> +  };
Pareil tu vas voir beaucoup plus simple a gérer avec `react-hook-form` :)

2023-08-22 18:02 UTC, MisterAzix commented on prisma/schema.prisma
Attention à pas commit encore une fois :)

(T'as besoin de changer l'URL que quand tu fais un migration, sinon tu peux garder `env("DATABASE_URL")`

2023-08-22 18:02 UTC, MisterAzix commented on libs/kit-ui/src/lib/components/Molecules/InputGroup/InputGroup.tsx
Pas besoin de le modifier, ça va être gérer par `react-hook-form` :)

2023-08-22 19:13 UTC, benoitfvr commented on apps/front-client/src/features/sidebar/hooks/useUpdateUser.ts
> +      Authorization: `Bearer ${access_token}`,
Ce n'est pas ça, il y était avant, marche pas non plus

2023-08-22 20:47 UTC, MisterAzix reviewed
Bah écoute ça m'a l'air pas mal 👀

2023-08-22 20:47 UTC, MisterAzix commented on apps/front-client/src/features/sidebar/hooks/index.ts
`hooks` et `types` ça sert plus ici nan ?

2023-08-22 20:47 UTC, MisterAzix commented on apps/front-client/src/features/profile/components/Organisms/UpdateUserForm.tsx
> +`;
Tu peux à la limite les mettre dans un dossier Atoms, mais pas obligatoire, comme tu veux.

Faudrait par contre que je change un poil le composant Text pour qu'on puisse l'utiliser à la place de styliser à chaque fois le Typo à la main.

2023-08-22 22:58 UTC, benoitfvr commented on apps/front-client/src/features/sidebar/hooks/index.ts
Ca n'a jamais servi ici mdr, je m'étais juste gouré de dossier

2023-08-23 07:52 UTC, MisterAzix submitted a review, later dismissed
Juste un petit tips mais sinon good, les requêtes passent toujours pas ? 🤔

2023-08-23 07:52 UTC, MisterAzix commented on apps/front-client/src/features/profile/components/Atoms/AlertMessage.tsx
> +
Alors c'est pas faux mais pro tips tu peux faire juste ça :)

```suggestion
import styled from '@emotion/styled';
import { palette, typography } from '@hetic-saline-royale-academy/kit-ui';
import { Typography } from '@mui/material';

const Alert = styled(Typography)`
  color: ${palette.error[500]};
  ${typography.xs.medium};
`;

export default Alert;
```

2023-08-23 08:04 UTC, MisterAzix commented on apps/front-client/src/features/profile/hooks/useUpdateUser.ts
> +  const response = await fetch(`${process.env.API_URL}/user/${id}`, {
Okay alors tu peux éventuellement tester ça : dans ton next config remplace :
```ts
  env: {
    API_URL: process.env.API_URL + '/api' || 'http://localhost:3000/api',
  },
```
par :
```ts
  env: {
    API_URL: process.env.API_URL || 'http://localhost:3000',
  },
```

Et ensuite ici
```suggestion
  const url = new URL(`/api/user/${id}`, process.env.API_URL);
  const response = await fetch(url, {
```

2023-08-23 15:17 UTC, MisterAzix approved these changes

2023-08-23 15:22 UTC, merged