Feat/progress page
MisterAzix/hetic-saline-royale-academy pull request #87
Opened 2023-09-04 09:35 UTC by benoitfvr

## Ticket

## Infos

2023-09-11 14:54 UTC, justinDev91 requested changes

2023-09-11 14:54 UTC, justinDev91 commented on apps/api/src/app/course/dto/create-course.dto.ts
> -  progress_tracking_id?: string;
why ? @benoitfvr ! Tout changement de model doit être communiqué de peur de casser tout ce qui est fait jusqu'à présent .

2023-09-11 14:54 UTC, justinDev91 commented on apps/api/src/app/course/dto/create-course.dto.ts
>    @IsObject()
A supprimer. C'est une source de bug

2023-09-11 14:54 UTC, justinDev91 commented on apps/api/src/app/course/entities/course.entity.ts
> -  progress_tracking_id: string;
??

2023-09-11 14:54 UTC, justinDev91 commented on apps/api/src/app/gamification/dto/create-gamification.dto.ts
> -
??

2023-09-11 14:54 UTC, justinDev91 commented on apps/api/src/app/gamification/entities/gamification.entity.ts
> -
Remplacé par masteclass_tracker_id ?

2023-09-11 14:54 UTC, justinDev91 commented on apps/api/src/app/progress_tracker/dto/create-progress_tracker.dto.ts
> -import { ApiProperty } from '@nestjs/swagger';
Deleted et remplacé par quoi ? On devait techniquement avoir un progress tracker masterClass et un progress cours !

2023-09-11 14:54 UTC, justinDev91 commented on apps/front-admin/src/features/masterclass/components/Organisms/MasterclassTable.tsx
> +const dateFormatter = new Intl.DateTimeFormat('fr-FR', {
Ça  devrait être dans un fichier utils

2023-09-11 14:54 UTC, justinDev91 commented on apps/front-admin/src/features/masterclass/components/Organisms/MasterclassTable.tsx
>  const MasterclassTable = () => {
Je ne vois pas le lien de ce composant avec ton ticket @benoitfvr

2023-09-11 14:55 UTC, justinDev91 commented
Tu as bcp bossé bravo @benoitfvr. Tiens moi moi au courant qu'on puisse review ta PR ensemble ,il y a pas mal des chose à revoir ou à changer.

2023-09-11 14:56 UTC, justinDev91 commented
Peut-tu y mettre une petite vidéo pour illustré le fonctionnement de progressMasterClass @benoitfvr 
?

2023-09-16 10:33 UTC, benoitfvr commented on apps/api/src/app/progress_tracker/dto/create-progress_tracker.dto.ts
> -import { ApiProperty } from '@nestjs/swagger';
J'ai viré le progress_tracker qui ne servait à rien au final, on ne s'en sert pas. On utilise directement Progress qui regroupe tout

2023-09-16 10:34 UTC, benoitfvr commented on apps/front-admin/src/features/masterclass/components/Organisms/MasterclassTable.tsx
>  const MasterclassTable = () => {
Si, on affiche les masterclass et leur progression dans la page Progress

2023-09-16 12:48 UTC, MisterAzix approved these changes, later dismissed
LGTM

2023-09-16 13:38 UTC, MisterAzix approved these changes

2023-09-16 13:45 UTC, merged