feat: add VideoPlayer component
MisterAzix/hetic-saline-royale-academy pull request #93
Opened 2023-09-05 18:55 UTC by Triips-TheCoder

## Ticket
https://www.notion.so/ETQ-dev-JV-cr-er-le-composant-Video-player-c020791945a34980a1e9fd3f32f8588b?pvs=4

## Infos
Sur cette PR j'ai rajouté le composant VideoPlayer responsive il manque juste d'handle le cas ou l'utilisateur met son téléphone en landscape mais on pourra le rajouter plus tard ce n'est pas grave je ne pense pas que ça prend beaucoup de temps ⌛ 

## Screen
![Capture d’écran 2023-09-05 à 20 55 11](https://github.com/MisterAzix/hetic-saline-royale-academy/assets/73161461/4bbbe698-a7ee-4d9d-b573-1dc9e90ce72c)

Je ne peux pas mettre de vidéo de preview car le fichier est trop lourd il dépasse 10 mo

2023-09-05 20:26 UTC, MisterAzix requested changes
Juste l'URL à gérer, sinon le format c'est pas bien grave ça fonctionne mais voilà l'Internationalization API existe :)

2023-09-05 20:26 UTC, MisterAzix commented on libs/kit-ui/src/lib/components/Organism/VideoPlayer/VideoPlayer.tsx
> +}
Bah c'est quoi ça monsieur ? 👀 

https://developer.mozilla.org/fr/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat

2023-09-05 20:26 UTC, MisterAzix commented on libs/kit-ui/src/lib/components/Organism/VideoPlayer/VideoPlayer.tsx
> +              url="http://commondatastorage.googleapis.com/gtv-videos-bucket/sample/TearsOfSteel.mp4"
Comment je mets ma propre URL :)

2023-09-06 08:22 UTC, benoitfvr approved these changes

2023-09-06 08:22 UTC, MisterAzix approved these changes

2023-09-06 08:24 UTC, justinDev91 approved these changes

2023-09-06 08:25 UTC, merged