feat(front-client): allow user to subscribe to courses from explorer …
MisterAzix/hetic-saline-royale-academy pull request #97
Opened 2023-09-13 18:50 UTC by justinDev91

…party 1

## Ticket
ETQ client JVP  Display all courses in explorer and allow user to  subscribe to courses

## Infos

2023-09-13 19:31 UTC, MisterAzix requested changes

2023-09-13 19:31 UTC, MisterAzix commented on apps/front-client/src/features/courses/utils/getRelativeTimeString.ts
> +//TODO: Fix type error @maxence
?

2023-09-13 19:31 UTC, MisterAzix commented on apps/front-client/src/features/explore/components/Organisms/CourseListe.tsx
> +    }
Pas besoin de try catch c'est déjà géré par `react-query`

2023-09-13 19:31 UTC, MisterAzix commented on apps/front-client/src/features/explore/components/Organisms/CourseListe.tsx
> +    }
\+ on évite les console.log en front :)

2023-09-13 19:31 UTC, MisterAzix commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +  return { uploadCourse: mutate, isLoading, isError };
```suggestion
  return { updateCourse: mutate, isLoading, isError };
```

2023-09-13 19:31 UTC, MisterAzix commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +  formData.append('user_id', user_id);
Ça ne sert pas 👀 
```suggestion
```

2023-09-13 19:31 UTC, MisterAzix commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +  );
Rajoute le onSuccess et tu invalidates les cours react-query va donc re-fetch et ça va update ton UI.

2023-09-14 08:47 UTC, justinDev91 commented on apps/front-client/src/features/courses/utils/getRelativeTimeString.ts
> +//TODO: Fix type error @maxence
Tu as remplacé ma solution moment avec  ça et tu l'avait visiblement pas testé. Lance le server front-client. Il y a un bug de type que tu dois résoudre stp. @MisterAzix

2023-09-14 08:49 UTC, justinDev91 commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +  return { uploadCourse: mutate, isLoading, isError };
Bien vu

2023-09-14 08:50 UTC, justinDev91 commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +  formData.append('user_id', user_id);
Bien vu.

2023-09-14 08:55 UTC, justinDev91 commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +  );
Bien vu bg @MisterAzix

2023-09-14 09:09 UTC, MisterAzix commented on apps/front-client/src/features/courses/utils/getRelativeTimeString.ts
> +//TODO: Fix type error @maxence
Tu peux rebase, je viens de fix

2023-09-14 09:13 UTC, MisterAzix requested changes

2023-09-14 09:13 UTC, MisterAzix commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +        await router.push(routes.explore);
Oula... bah non monsieur tu nous fais quoi là ?
```suggestion
        await queryClient.invalidateQueries({
          queryKey: [COURSE_KEY],
        });
```

2023-09-14 09:13 UTC, MisterAzix commented on apps/front-client/src/features/explore/components/Organisms/CourseListe.tsx
> +  };
Bon du coup ça fait bizarre d'avoir une fonction qui englobe une autre fonction, c'est un peu redondant mais soit.

2023-09-14 09:13 UTC, MisterAzix commented on apps/front-client/src/features/courses/components/Organisms/CourseDetail.tsx
> +  // const daysDifference = getRelativeTimeString(course.updated_at || new Date());
J'ai fix du coup à corriger stp

2023-09-14 10:20 UTC, justinDev91 commented on apps/front-client/src/features/explore/hooks/useUpdateCourse.ts
> +        await router.push(routes.explore);
Oulà !! Pas fait gaffe.

2023-09-14 10:21 UTC, justinDev91 commented on apps/front-client/src/features/explore/components/Organisms/CourseListe.tsx
> +  };
Ouais. Dans tout le cas? Ce n'est pas clean

2023-09-14 10:24 UTC, justinDev91 commented on apps/front-client/src/features/courses/components/Organisms/CourseDetail.tsx
> +  // const daysDifference = getRelativeTimeString(course.updated_at || new Date());
Dak

2023-09-14 10:35 UTC, justinDev91 commented
J'en ai profiter pour revoir le design sur la liste de masterclass @MisterAzix

2023-09-14 10:43 UTC, MisterAzix approved these changes
Allez vamos ça me va

2023-09-14 10:43 UTC, merged